In [1]:
import numpy as np

### 넘파이 ndarray
- [] : 1차원
- [[]] : 2차원

In [7]:
array1 = np.array([1,2,3])
print(type(array1), array1.ndim, array1.shape) #타입은 ndarray, 형태는 1차원 array, 3개의 데이터를 가짐

array2 = np.array([[1,2,3],[2,3,4]])
print(type(array2), array2.ndim, array2.shape) #타입은 ndarray, 형태는 2차원 array, 2개의 로우, 3개의 컬럼

array3 = np.array([[1,2,3]])
print(type(array3), array2.ndim, array3.shape) #타입은 ndarray, 형태는 2차원 array, 1개의 로우, 3개의 컬럼

<class 'numpy.ndarray'> 1 (3,)
<class 'numpy.ndarray'> 2 (2, 3)
<class 'numpy.ndarray'> 2 (1, 3)


#### ndarray의 데이터타입
- 한 ndarray 내의 데이터타입은 모두 같음. 다른 데이터 타입이 섞여 있을 경우, 더 큰 데이터 타입으로 변환.
- astype() 메서드 사용 가능.

In [9]:
list = [1,2,3]
print(type(list))
array1 = np.array(list)
print(type(array1), array1.dtype) #타입은 ndarray, 데이터타입은 int32

<class 'list'>
<class 'numpy.ndarray'> int32


In [10]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_int.dtype, array_float.dtype)

int32 float64


#### ndarray를 편리하게 생성하기 - arange, zeros, ones
- 주로 대규모의 데이터를 일괄적으로 초기화해야 할 경우 사용.

In [12]:
# arange
sequence_array = np.arange(10) #range() 함수와 유사. 0부터 9까지 연속 숫자 생성.
print(sequence_array, sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9] int32 (10,)


In [13]:
# zeros()
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array, zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]] int32 (3, 2)


In [14]:
# ones()
one_array = np.ones((3,2)) #dtype 지정 안해주면, float가 기본형
print(one_array, one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]] float64 (3, 2)


#### ndarray의 차원과 크기를 변경하는 reshape()
- .reshape((-1,1)) : 해당 ndarray를 2차원으로 변경. 1컬럼으로 고정해라. ex[[1],[2],..]

In [20]:
array1 = np.arange(10)
print(array1, array1.shape) #1차원 10데이터

array2 = array1.reshape(2,5)
print(array2, array2.shape) #2차원 2로우 5컬럼

array3 = array1.reshape(5,-1) # -1 : 5개의 로우를 고정하면, 컬럼 수는 정해짐.
print(array3, array3.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


In [24]:
array1 = np.arange(8)
print(array1, array1.shape) #1차원 8데이터

array2 = array1.reshape(2,2,2)
print(array2, array2.shape) #3차원 2로우 2컬럼

array3 = array1.reshape(-1,1)
print(array3, array3.shape) #2차원 ?로우 1컬럼

[0 1 2 3 4 5 6 7] (8,)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


#### ndarray의 데이터 세트 선택하기 - 인덱싱

In [33]:
# 단일 값 추출
array1 = np.arange(1,10)
value = array1[2] #3번째 인덱스 위치의 데이터값 의미
print(value)

array2 = array1.reshape(3,3)
value2 = array2[1,2] #2번째 로우의 3번째 컬럼 값
print(array2, value2)

3
[[1 2 3]
 [4 5 6]
 [7 8 9]] 6


In [42]:
# 슬라이싱
array1 = np.arange(1,10)
value = array1[:3] #0번째~2번째 데이터값 의미
print(value)

array2 = array1.reshape(3,3)
value2 = array2[:,2] #모든 로우, 3번째 컬럼값들
print(value2)

[1 2 3]
[3 6 9]


#### 행렬의 정렬 - sort()와 argsort()

In [46]:
org_array = np.array([3,1,9,5])
print(org_array)
sort_array = np.sort(org_array) #원본은 바꾸지 않는다.
print(sort_array)

sort_array2 = org_array.sort() #원본을 바꾼다.
print(sort_array2)
print(org_array)

[3 1 9 5]
[1 3 5 9]
None
[1 3 5 9]


In [47]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array) # 정렬했을 때 인덱스를 반환
print(sort_indices)

[1 0 3 2]


#### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [50]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


#### 전치 행렬

In [51]:
A = np.array([[1,2,3],
             [4,5,6]])

print(np.transpose(A))

[[1 4]
 [2 5]
 [3 6]]
